const locationsData = [
  {
    location_type_id: 1,
    location_name: 'vel turpis nunc',
    location_description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    address: '2310 N Monroe St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'a erat nam',
    location_description:
      'est ante in nibh mauris cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui accumsan',
    address: '\n222 W Knox Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'massa sed elementum',
    location_description:
      'massa sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget',
    address: '275-199 E Jackson Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99207',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'viverra suspendisse potenti',
    location_description:
      'dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris in',
    address: 'E Providence Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99207',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'vestibulum sed arcu',
    location_description:
      'ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est',
    address: '2426 N Addison St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99207',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'diam sollicitudin tempor',
    location_description:
      'nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat',
    address: '2602 N Hamilton St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99207',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'scelerisque varius morbi',
    location_description:
      'sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt',
    address: '2900 E 1st Ave ',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99202',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'elementum facilisis leo',
    location_description:
      'mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget duis at tellus at urna condimentum',
    address: '1204 W Joseph Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'vel turpis nunc',
    location_description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla condimentum, diam sed varius pharetra, sapien felis euismod neque, eget mattis nisl lacus ut diam. Praesent at orci tristique, cursus augue non, pulvinar nunc. Ut dolor mi, consequat et congue at, cursus sed lectus. Donec ipsum orci, blandit in viverra et, sagittis a dui. Vivamus faucibus tristique erat eu cursus.',
    address: 'Town and Country ',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99208',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'a erat nam',
    location_description:
      'Phasellus vel venenatis leo. Morbi sit amet erat a urna ultricies imperdiet ut non ante. Nam pharetra erat quis pharetra dignissim. Vestibulum nec ante quis augue auctor suscipit.',
    address: '300 W Hawthorne Rd',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99251',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'massa sed elementum',
    location_description:
      'Phasellus vehicula neque non nunc aliquam, vitae ornare est finibus.',
    address: '625 E Huron Dr',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99208',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'viverra suspendisse potenti',
    location_description:
      'Mauris faucibus est enim, in elementum metus venenatis vel. Nulla ultrices ipsum sed neque auctor,',
    address: '1424 S St Charles Rd',
    address_line2: '',
    city: 'Spokane Valley',
    state: 'WA',
    zip: '99037',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'vestibulum sed arcu',
    location_description:
      'Aenean quis lectus dui. Sed id lectus ac orci gravida bibendum nec vel sem. Ut lobortis elit dui, vitae interdum odio sodales vel. Integer porta purus turpis, id laoreet sapien aliquam eu. Ut et diam dignissim, pretium enim ac, elementum augue.',
    address: '1423 S Burns Rd',
    address_line2: '',
    city: 'Spokane Valley',
    state: 'WA',
    zip: '99037',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'scelerisque varius morbi',
    location_description:
      'massa sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget',
    address: '4302 S Cook St ',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99223',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'aliquam etiam erat',
    location_description:
      'dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris in',
    address: '4215 S Altamont St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99223',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'elementum facilisis leo',
    location_description:
      'ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est',
    address: '12424 N Fairwood Dr',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99218',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'vel turpis nunc',
    location_description:
      'nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat',
    address: '3404 W Woodland Blvd',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99224',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'a erat nam',
    location_description:
      'sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt',
    address: '7117 N Division St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99208',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'massa sed elementum',
    location_description:
      'id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis eget nunc lobortis',
    address: '7200 N Wall St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99208',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'viverra suspendisse potenti',
    location_description:
      'mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget duis at tellus at urna condimentum',
    address: '7905 N Division St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99208',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'vestibulum sed arcu',
    location_description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla condimentum, diam sed varius pharetra, sapien felis euismod neque, eget mattis nisl lacus ut diam. Praesent at orci tristique, cursus augue non, pulvinar nunc. Ut dolor mi, consequat et congue at, cursus sed lectus. Donec ipsum orci, blandit in viverra et, sagittis a dui. Vivamus faucibus tristique erat eu cursus.',
    address: '5601 E Sprague Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99212',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'diam sollicitudin tempor',
    location_description:
      'Phasellus vel venenatis leo. Morbi sit amet erat a urna ultricies imperdiet ut non ante. Nam pharetra erat quis pharetra dignissim. Vestibulum nec ante quis augue auctor suscipit.',
    address: '6311 E Sharp Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99212',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'scelerisque varius morbi',
    location_description:
      'Phasellus vehicula neque non nunc aliquam, vitae ornare est finibus.',
    address: '10212 E 9th Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99206',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'aliquam etiam erat',
    location_description:
      'Mauris faucibus est enim, in elementum metus venenatis vel. Nulla ultrices ipsum sed neque auctor,',
    address: '9415 E 4th Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99206',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'elementum facilisis leo',
    location_description:
      'Aenean quis lectus dui. Sed id lectus ac orci gravida bibendum nec vel sem. Ut lobortis elit dui, vitae interdum odio sodales vel. Integer porta purus turpis, id laoreet sapien aliquam eu. Ut et diam dignissim, pretium enim ac, elementum augue.',
    address: '1441 N Argonne Rd',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99212',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'vel turpis nunc',
    location_description:
      'est ante in nibh mauris cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui accumsan',
    address: '8403 E Broadway Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99212',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'a erat nam',
    location_description:
      'massa sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget',
    address: '9119 E Broadway Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99206',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'massa sed elementum',
    location_description:
      'dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris in',
    address: '227 W 24th Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99203',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'viverra suspendisse potenti',
    location_description:
      'ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est',
    address: '114 W 27th Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99203',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'vestibulum sed arcu',
    location_description:
      'nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat',
    address: '911 W 25th Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99203',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'diam sollicitudin tempor',
    location_description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    address: '2311 W 16th Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99224',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'scelerisque varius morbi',
    location_description:
      'est ante in nibh mauris cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui accumsan',
    address: '1001 S Assembly Rd',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99224',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'a erat nam',
    location_description:
      'nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat',
    address: '322 N Spokane Falls Ct',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99201',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'massa sed elementum',
    location_description:
      'sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt',
    address: '333 W Spokane Falls Blvd',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99201',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'vestibulum sed arcu',
    location_description:
      'mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget duis at tellus at urna condimentum',
    address: '675 S McClellan St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99204',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'diam sollicitudin tempor',
    location_description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    address: '3318 W Northwest Blvd',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'scelerisque varius morbi',
    location_description:
      'est ante in nibh mauris cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui accumsan',
    address: '165 S Post St,',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99201',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'aliquam etiam erat',
    location_description:
      'massa sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget',
    address: '621 W Mallon Avenue',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99201',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'elementum facilisis leo',
    location_description:
      'dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris in',
    address: '10 S Post St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99201',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'vel turpis nunc',
    location_description:
      'ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est',
    address: '111 S Post St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99201',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'a erat nam',
    location_description:
      'nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat',
    address: '1007 W 1st Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99201',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'massa sed elementum',
    location_description:
      'sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt',
    address: '159 S Lincoln St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99201',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'viverra suspendisse potenti',
    location_description:
      'id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis eget nunc lobortis',
    address: '152 S Monroe St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99201',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'vestibulum sed arcu',
    location_description:
      'mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget duis at tellus at urna condimentum',
    address: '224 S Lincoln St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99201',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'diam sollicitudin tempor',
    location_description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    address: '430 W Main Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99201',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'scelerisque varius morbi',
    location_description:
      'est ante in nibh mauris cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui accumsan',
    address: '808 W. Spokane Falls Blvd.',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99201',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'aliquam etiam erat',
    location_description:
      'massa sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget',
    address: '44 W. Riverside Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99201',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'elementum facilisis leo',
    location_description:
      'dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris in',
    address: '1001 E. North Foothills Dr.',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99207',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'vel turpis nunc',
    location_description:
      'ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est',
    address: '6616 N Addison St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99208',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'aliquam etiam erat',
    location_description:
      'massa sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget',
    address: '3919 N Maple St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'elementum facilisis leo',
    location_description:
      'dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris in',
    address: '1203 W Glass Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'vel turpis nunc',
    location_description:
      'ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est',
    address: '3718 N Monroe St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'a erat nam',
    location_description:
      'nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat',
    address: '3222 N Post St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'massa sed elementum',
    location_description:
      'sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt',
    address: '3315 N Lincoln St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'viverra suspendisse potenti',
    location_description:
      'id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis eget nunc lobortis',
    address: '1111 W Dalton Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'diam sollicitudin tempor',
    location_description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    address: '1207 E 38th Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99203',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'scelerisque varius morbi',
    location_description:
      'est ante in nibh mauris cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui accumsan',
    address: '1021 W 15th Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99203',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'aliquam etiam erat',
    location_description:
      'massa sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget',
    address: '618 S Oak St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99204',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'elementum facilisis leo',
    location_description:
      'dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris in',
    address: '602 N Walnut St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99206',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'vel turpis nunc',
    location_description:
      'ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est',
    address: '1815 N Post St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'a erat nam',
    location_description:
      'nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat',
    address: '1607 W Mansfield Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'massa sed elementum',
    location_description:
      'sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt',
    address: '234 W Park Pl',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'viverra suspendisse potenti',
    location_description:
      'id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis eget nunc lobortis',
    address: '4620 N Stevens St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'vestibulum sed arcu',
    location_description:
      'mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget duis at tellus at urna condimentum',
    address: '5725 N Wall St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'diam sollicitudin tempor',
    location_description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    address: '7200 N Wall St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99208',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'scelerisque varius morbi',
    location_description:
      'est ante in nibh mauris cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui accumsan',
    address: '1222 E Winchester Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99218',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'elementum facilisis leo',
    location_description:
      'dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris in',
    address: '13619 N Shady Slope Rd',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99208',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'vel turpis nunc',
    location_description:
      'ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est',
    address: '14709 N Yale Rd',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99021',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 2,
    location_name: 'a erat nam',
    location_description:
      'nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat',
    address: '3908 E Birch St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99217',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'massa sed elementum',
    location_description:
      'sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt',
    address: '819 E Rosewood Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99208',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 4,
    location_name: 'viverra suspendisse potenti',
    location_description:
      'id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis eget nunc lobortis',
    address: '5003 N Stevens St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 1,
    location_name: 'vestibulum sed arcu',
    location_description:
      'mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget duis at tellus at urna condimentum',
    address: '3605 N Alberta St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99205',
    county: ' Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'aliquam etiam erat',
    location_description:
      'massa sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget',
    address: '12321 N Pittsburg St',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99218',
    county: 'Spokane County',
    country: 'United States',
  },
  {
    location_type_id: 3,
    location_name: 'vestibulum sed arcu',
    location_description:
      'mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget duis at tellus at urna condimentum',
    address: '1333 E 29th Ave',
    address_line2: '',
    city: 'Spokane',
    state: 'WA',
    zip: '99203',
    county: 'Spokane County',
    country: 'United States',
  },
];

module.exports = locationsData;
